export type DDI = {
  code: string    // "+55"
  country: string // "Brasil"
  flag: string    // "🇧🇷"
}

/**
 * Lista completa de DDIs (ITU-T E.164).
 * Ordenada: Brasil primeiro, depois os mais usados pela agência, depois
 * todos os demais em ordem de código numérico.
 */
export const DDI_LIST: DDI[] = [
  // ── Prioritários ──────────────────────────────────────────────────────────
  { code: "+55",  country: "Brasil",               flag: "🇧🇷" },
  { code: "+351", country: "Portugal",              flag: "🇵🇹" },
  { code: "+54",  country: "Argentina",             flag: "🇦🇷" },
  { code: "+598", country: "Uruguai",               flag: "🇺🇾" },
  { code: "+595", country: "Paraguai",              flag: "🇵🇾" },
  { code: "+56",  country: "Chile",                 flag: "🇨🇱" },
  { code: "+57",  country: "Colômbia",              flag: "🇨🇴" },
  { code: "+52",  country: "México",                flag: "🇲🇽" },
  { code: "+1",   country: "EUA / Canadá",          flag: "🇺🇸" },
  { code: "+44",  country: "Reino Unido",           flag: "🇬🇧" },
  { code: "+33",  country: "França",                flag: "🇫🇷" },
  { code: "+49",  country: "Alemanha",              flag: "🇩🇪" },
  { code: "+34",  country: "Espanha",               flag: "🇪🇸" },
  { code: "+39",  country: "Itália",                flag: "🇮🇹" },
  // ── América do Sul ────────────────────────────────────────────────────────
  { code: "+51",  country: "Peru",                  flag: "🇵🇪" },
  { code: "+58",  country: "Venezuela",             flag: "🇻🇪" },
  { code: "+591", country: "Bolívia",               flag: "🇧🇴" },
  { code: "+593", country: "Equador",               flag: "🇪🇨" },
  { code: "+592", country: "Guiana",                flag: "🇬🇾" },
  { code: "+594", country: "Guiana Francesa",       flag: "🇬🇫" },
  { code: "+596", country: "Martinica",             flag: "🇲🇶" },
  { code: "+597", country: "Suriname",              flag: "🇸🇷" },
  // ── América Central e Caribe ──────────────────────────────────────────────
  { code: "+501", country: "Belize",                flag: "🇧🇿" },
  { code: "+502", country: "Guatemala",             flag: "🇬🇹" },
  { code: "+503", country: "El Salvador",           flag: "🇸🇻" },
  { code: "+504", country: "Honduras",              flag: "🇭🇳" },
  { code: "+505", country: "Nicarágua",             flag: "🇳🇮" },
  { code: "+506", country: "Costa Rica",            flag: "🇨🇷" },
  { code: "+507", country: "Panamá",                flag: "🇵🇦" },
  { code: "+509", country: "Haiti",                 flag: "🇭🇹" },
  { code: "+53",  country: "Cuba",                  flag: "🇨🇺" },
  { code: "+1809",country: "República Dominicana",  flag: "🇩🇴" },
  { code: "+1787",country: "Porto Rico",            flag: "🇵🇷" },
  { code: "+1876",country: "Jamaica",               flag: "🇯🇲" },
  { code: "+1868",country: "Trinidad e Tobago",     flag: "🇹🇹" },
  { code: "+1246",country: "Barbados",              flag: "🇧🇧" },
  { code: "+1242",country: "Bahamas",               flag: "🇧🇸" },
  { code: "+1473",country: "Granada",               flag: "🇬🇩" },
  { code: "+1784",country: "São Vicente",           flag: "🇻🇨" },
  { code: "+1758",country: "Santa Lúcia",           flag: "🇱🇨" },
  { code: "+1767",country: "Dominica",              flag: "🇩🇲" },
  { code: "+1268",country: "Antígua e Barbuda",     flag: "🇦🇬" },
  { code: "+1869",country: "São Cristóvão e Névis", flag: "🇰🇳" },
  // ── Europa ────────────────────────────────────────────────────────────────
  { code: "+30",  country: "Grécia",                flag: "🇬🇷" },
  { code: "+31",  country: "Países Baixos",         flag: "🇳🇱" },
  { code: "+32",  country: "Bélgica",               flag: "🇧🇪" },
  { code: "+36",  country: "Hungria",               flag: "🇭🇺" },
  { code: "+40",  country: "Romênia",               flag: "🇷🇴" },
  { code: "+41",  country: "Suíça",                 flag: "🇨🇭" },
  { code: "+43",  country: "Áustria",               flag: "🇦🇹" },
  { code: "+45",  country: "Dinamarca",             flag: "🇩🇰" },
  { code: "+46",  country: "Suécia",                flag: "🇸🇪" },
  { code: "+47",  country: "Noruega",               flag: "🇳🇴" },
  { code: "+48",  country: "Polônia",               flag: "🇵🇱" },
  { code: "+350", country: "Gibraltar",             flag: "🇬🇮" },
  { code: "+352", country: "Luxemburgo",            flag: "🇱🇺" },
  { code: "+353", country: "Irlanda",               flag: "🇮🇪" },
  { code: "+354", country: "Islândia",              flag: "🇮🇸" },
  { code: "+355", country: "Albânia",               flag: "🇦🇱" },
  { code: "+356", country: "Malta",                 flag: "🇲🇹" },
  { code: "+357", country: "Chipre",                flag: "🇨🇾" },
  { code: "+358", country: "Finlândia",             flag: "🇫🇮" },
  { code: "+359", country: "Bulgária",              flag: "🇧🇬" },
  { code: "+370", country: "Lituânia",              flag: "🇱🇹" },
  { code: "+371", country: "Letônia",               flag: "🇱🇻" },
  { code: "+372", country: "Estônia",               flag: "🇪🇪" },
  { code: "+373", country: "Moldávia",              flag: "🇲🇩" },
  { code: "+374", country: "Armênia",               flag: "🇦🇲" },
  { code: "+375", country: "Bielorrússia",          flag: "🇧🇾" },
  { code: "+376", country: "Andorra",               flag: "🇦🇩" },
  { code: "+377", country: "Mônaco",                flag: "🇲🇨" },
  { code: "+378", country: "San Marino",            flag: "🇸🇲" },
  { code: "+380", country: "Ucrânia",               flag: "🇺🇦" },
  { code: "+381", country: "Sérvia",                flag: "🇷🇸" },
  { code: "+382", country: "Montenegro",            flag: "🇲🇪" },
  { code: "+383", country: "Kosovo",                flag: "🇽🇰" },
  { code: "+385", country: "Croácia",               flag: "🇭🇷" },
  { code: "+386", country: "Eslovênia",             flag: "🇸🇮" },
  { code: "+387", country: "Bósnia e Herzegovina",  flag: "🇧🇦" },
  { code: "+389", country: "Macedônia do Norte",    flag: "🇲🇰" },
  { code: "+420", country: "República Tcheca",      flag: "🇨🇿" },
  { code: "+421", country: "Eslováquia",            flag: "🇸🇰" },
  { code: "+423", country: "Liechtenstein",         flag: "🇱🇮" },
  // ── Mediterrâneo / Ilhas Atlânticas ───────────────────────────────────────
  { code: "+298", country: "Ilhas Faroe",           flag: "🇫🇴" },
  { code: "+299", country: "Groenlândia",           flag: "🇬🇱" },
  { code: "+290", country: "Santa Helena",          flag: "🇸🇭" },
  { code: "+239", country: "São Tomé e Príncipe",   flag: "🇸🇹" },
  // ── África ────────────────────────────────────────────────────────────────
  { code: "+20",  country: "Egito",                 flag: "🇪🇬" },
  { code: "+212", country: "Marrocos",              flag: "🇲🇦" },
  { code: "+213", country: "Argélia",               flag: "🇩🇿" },
  { code: "+216", country: "Tunísia",               flag: "🇹🇳" },
  { code: "+218", country: "Líbia",                 flag: "🇱🇾" },
  { code: "+220", country: "Gâmbia",                flag: "🇬🇲" },
  { code: "+221", country: "Senegal",               flag: "🇸🇳" },
  { code: "+222", country: "Mauritânia",            flag: "🇲🇷" },
  { code: "+223", country: "Mali",                  flag: "🇲🇱" },
  { code: "+224", country: "Guiné",                 flag: "🇬🇳" },
  { code: "+225", country: "Costa do Marfim",       flag: "🇨🇮" },
  { code: "+226", country: "Burkina Faso",          flag: "🇧🇫" },
  { code: "+227", country: "Níger",                 flag: "🇳🇪" },
  { code: "+228", country: "Togo",                  flag: "🇹🇬" },
  { code: "+229", country: "Benin",                 flag: "🇧🇯" },
  { code: "+230", country: "Maurício",              flag: "🇲🇺" },
  { code: "+231", country: "Libéria",               flag: "🇱🇷" },
  { code: "+232", country: "Serra Leoa",            flag: "🇸🇱" },
  { code: "+233", country: "Gana",                  flag: "🇬🇭" },
  { code: "+234", country: "Nigéria",               flag: "🇳🇬" },
  { code: "+235", country: "Chade",                 flag: "🇹🇩" },
  { code: "+236", country: "República Centro-Africana", flag: "🇨🇫" },
  { code: "+237", country: "Camarões",              flag: "🇨🇲" },
  { code: "+238", country: "Cabo Verde",            flag: "🇨🇻" },
  { code: "+240", country: "Guiné Equatorial",      flag: "🇬🇶" },
  { code: "+241", country: "Gabão",                 flag: "🇬🇦" },
  { code: "+242", country: "República do Congo",    flag: "🇨🇬" },
  { code: "+243", country: "RD Congo",              flag: "🇨🇩" },
  { code: "+244", country: "Angola",                flag: "🇦🇴" },
  { code: "+245", country: "Guiné-Bissau",          flag: "🇬🇼" },
  { code: "+246", country: "Território Brit. Índico", flag: "🇮🇴" },
  { code: "+247", country: "Ilha Ascensão",         flag: "🇸🇭" },
  { code: "+248", country: "Seychelles",            flag: "🇸🇨" },
  { code: "+249", country: "Sudão",                 flag: "🇸🇩" },
  { code: "+250", country: "Ruanda",                flag: "🇷🇼" },
  { code: "+251", country: "Etiópia",               flag: "🇪🇹" },
  { code: "+252", country: "Somália",               flag: "🇸🇴" },
  { code: "+253", country: "Djibuti",               flag: "🇩🇯" },
  { code: "+254", country: "Quênia",                flag: "🇰🇪" },
  { code: "+255", country: "Tanzânia",              flag: "🇹🇿" },
  { code: "+256", country: "Uganda",                flag: "🇺🇬" },
  { code: "+257", country: "Burundi",               flag: "🇧🇮" },
  { code: "+258", country: "Moçambique",            flag: "🇲🇿" },
  { code: "+260", country: "Zâmbia",                flag: "🇿🇲" },
  { code: "+261", country: "Madagascar",            flag: "🇲🇬" },
  { code: "+262", country: "Reunião",               flag: "🇷🇪" },
  { code: "+263", country: "Zimbábue",              flag: "🇿🇼" },
  { code: "+264", country: "Namíbia",               flag: "🇳🇦" },
  { code: "+265", country: "Malawi",                flag: "🇲🇼" },
  { code: "+266", country: "Lesoto",                flag: "🇱🇸" },
  { code: "+267", country: "Botsuana",              flag: "🇧🇼" },
  { code: "+268", country: "Essuatíni",             flag: "🇸🇿" },
  { code: "+269", country: "Comores",               flag: "🇰🇲" },
  { code: "+27",  country: "África do Sul",         flag: "🇿🇦" },
  // ── Oriente Médio ─────────────────────────────────────────────────────────
  { code: "+90",  country: "Turquia",               flag: "🇹🇷" },
  { code: "+92",  country: "Paquistão",             flag: "🇵🇰" },
  { code: "+93",  country: "Afeganistão",           flag: "🇦🇫" },
  { code: "+94",  country: "Sri Lanka",             flag: "🇱🇰" },
  { code: "+95",  country: "Myanmar",               flag: "🇲🇲" },
  { code: "+98",  country: "Irã",                   flag: "🇮🇷" },
  { code: "+961", country: "Líbano",                flag: "🇱🇧" },
  { code: "+962", country: "Jordânia",              flag: "🇯🇴" },
  { code: "+963", country: "Síria",                 flag: "🇸🇾" },
  { code: "+964", country: "Iraque",                flag: "🇮🇶" },
  { code: "+965", country: "Kuwait",                flag: "🇰🇼" },
  { code: "+966", country: "Arábia Saudita",        flag: "🇸🇦" },
  { code: "+967", country: "Iêmen",                 flag: "🇾🇪" },
  { code: "+968", country: "Omã",                   flag: "🇴🇲" },
  { code: "+970", country: "Palestina",             flag: "🇵🇸" },
  { code: "+971", country: "Emirados Árabes",       flag: "🇦🇪" },
  { code: "+972", country: "Israel",                flag: "🇮🇱" },
  { code: "+973", country: "Bahrein",               flag: "🇧🇭" },
  { code: "+974", country: "Catar",                 flag: "🇶🇦" },
  { code: "+975", country: "Butão",                 flag: "🇧🇹" },
  { code: "+976", country: "Mongólia",              flag: "🇲🇳" },
  { code: "+977", country: "Nepal",                 flag: "🇳🇵" },
  // ── Ásia ──────────────────────────────────────────────────────────────────
  { code: "+7",   country: "Rússia / Cazaquistão",  flag: "🇷🇺" },
  { code: "+81",  country: "Japão",                 flag: "🇯🇵" },
  { code: "+82",  country: "Coreia do Sul",         flag: "🇰🇷" },
  { code: "+84",  country: "Vietnã",                flag: "🇻🇳" },
  { code: "+86",  country: "China",                 flag: "🇨🇳" },
  { code: "+852", country: "Hong Kong",             flag: "🇭🇰" },
  { code: "+853", country: "Macau",                 flag: "🇲🇴" },
  { code: "+855", country: "Camboja",               flag: "🇰🇭" },
  { code: "+856", country: "Laos",                  flag: "🇱🇦" },
  { code: "+880", country: "Bangladesh",            flag: "🇧🇩" },
  { code: "+886", country: "Taiwan",                flag: "🇹🇼" },
  { code: "+91",  country: "Índia",                 flag: "🇮🇳" },
  { code: "+960", country: "Maldivas",              flag: "🇲🇻" },
  { code: "+992", country: "Tadjiquistão",          flag: "🇹🇯" },
  { code: "+993", country: "Turcomenistão",         flag: "🇹🇲" },
  { code: "+994", country: "Azerbaijão",            flag: "🇦🇿" },
  { code: "+995", country: "Geórgia",               flag: "🇬🇪" },
  { code: "+996", country: "Quirguistão",           flag: "🇰🇬" },
  { code: "+998", country: "Uzbequistão",           flag: "🇺🇿" },
  // ── Sudeste Asiático / Oceania ─────────────────────────────────────────────
  { code: "+60",  country: "Malásia",               flag: "🇲🇾" },
  { code: "+61",  country: "Austrália",             flag: "🇦🇺" },
  { code: "+62",  country: "Indonésia",             flag: "🇮🇩" },
  { code: "+63",  country: "Filipinas",             flag: "🇵🇭" },
  { code: "+64",  country: "Nova Zelândia",         flag: "🇳🇿" },
  { code: "+65",  country: "Singapura",             flag: "🇸🇬" },
  { code: "+66",  country: "Tailândia",             flag: "🇹🇭" },
  { code: "+670", country: "Timor-Leste",           flag: "🇹🇱" },
  { code: "+675", country: "Papua Nova Guiné",      flag: "🇵🇬" },
  { code: "+676", country: "Tonga",                 flag: "🇹🇴" },
  { code: "+677", country: "Ilhas Salomão",         flag: "🇸🇧" },
  { code: "+678", country: "Vanuatu",               flag: "🇻🇺" },
  { code: "+679", country: "Fiji",                  flag: "🇫🇯" },
  { code: "+680", country: "Palau",                 flag: "🇵🇼" },
  { code: "+685", country: "Samoa",                 flag: "🇼🇸" },
  { code: "+686", country: "Kiribati",              flag: "🇰🇮" },
  { code: "+687", country: "Nova Caledônia",        flag: "🇳🇨" },
  { code: "+689", country: "Polinésia Francesa",    flag: "🇵🇫" },
  { code: "+690", country: "Tokelau",               flag: "🇹🇰" },
  { code: "+691", country: "Micronésia",            flag: "🇫🇲" },
  { code: "+692", country: "Ilhas Marshall",        flag: "🇲🇭" },
]

/** DDI padrão do sistema. */
export const DDI_DEFAULT = "+55"

/**
 * Retorna a entrada DDI pelo código (ex: "+55") ou o default se não achar.
 */
export function getDDI(code: string): DDI {
  return DDI_LIST.find((d) => d.code === code) ?? { code: "+55", country: "Brasil", flag: "🇧🇷" }
}

/**
 * Normaliza string para busca: remove acentos, minúsculas, sem espaços extras.
 */
export function normalizarBusca(s: string): string {
  return s
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .toLowerCase()
    .trim()
}
